[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"


[project]
name = "dataset-analyzer"
version = "0.1.0"
description = "A command line dataset analysis tool"
requires-python = ">=3.11"
dependencies = [
    "pandas",
    "pytest"
    "pyyaml",
]


[project.scripts]
dataset-analyzer = "dataset_analyzer.cli:main"